services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescale_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: timeseries_db
      PGDATA: /DB/postgresql/data/pgdata
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./DB/postgresql/init_script.sql:/docker-entrypoint-initdb.d/init_script.sql      - ./backup:/backup
    ports:
      - "5432:5432"
    restart: unless-stopped
    command: >
      postgres -c shared_preload_libraries=timescaledb
    networks:
      - app-network
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadminIS
    environment:
      PGADMIN_DEFAULT_EMAIL: "ajsoi@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "1111"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin_config:/var/lib/pgadmin/pgadmin4
    networks:
      - app-network
volumes:
  timescale_data:
    driver: local
  pgadmin_data:

networks:
  app-network:
    driver: bridge
